name: CI/CD for Churn Prediction

on:
  push:
    branches:
      - main  # Déclenche le CI/CD à chaque push sur la branche principale

jobs:
  build:
    runs-on: ubuntu-latest  # Utilise une machine Ubuntu pour l'exécution


    steps:
    - name: Récupérer le code du repo
      uses: actions/checkout@v2

    - name: Installer Python
      uses: actions/setup-python@v2
      with:
        python-version: "3.9"

    - name: Installer les dépendances
      run: |
        pip install -r requirements.txt

    - name: Lancer les tests
      run: |
        python -m unittest discover tests || echo "Pas de tests trouvés"
